### ISSUE TITLE
Unable to load photos

### ISSUE THREAD

**Issue by yliu342** [nishadh/photos-sample-app#1]
Hi Nish, 

This is YaKun from Vend. I was looking at your code and trying to run it on a simulator. However I was unable to add any photos. When I press the + button the app seems to be stuck in a loading state. Anything in particular I need to do to get it running?

![Screen Shot 2021-02-22 at 12 19 40 PM](https://user-images.githubusercontent.com/8564158/108643862-435d1680-7511-11eb-8299-49aa81bc50ba.png)

**Comment by nishadh** [comment]
Hi Yakun

Could you please try it on one of the newer Android versions? Like API 28.
I used some new Android tools and components and didn't have time to look
more at backward compatibility.


Thanks
Nishadh

**Comment by nishadh** [comment]
Thanks for reaching out by the way. And I was actually mostly developing
using real device so there could be some other issues with Emulator but I
would try upgraded emulator first.


Warm regards
Nishadh

**Comment by yliu342** [comment]
Hi Nishadh,
Using API 30 simulator works. Thank you

**Comment by nishadh** [comment]
Thanks for reaching out and trying again Yakun.
